/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SimuladorTransacaoIndividualRouteImport } from './routes/simulador-transacao-individual'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SimuladorTransacaoIndividualRoute =
  SimuladorTransacaoIndividualRouteImport.update({
    id: '/simulador-transacao-individual',
    path: '/simulador-transacao-individual',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/simulador-transacao-individual': typeof SimuladorTransacaoIndividualRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/simulador-transacao-individual': typeof SimuladorTransacaoIndividualRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/simulador-transacao-individual': typeof SimuladorTransacaoIndividualRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/simulador-transacao-individual'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/simulador-transacao-individual'
  id: '__root__' | '/' | '/simulador-transacao-individual'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SimuladorTransacaoIndividualRoute: typeof SimuladorTransacaoIndividualRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulador-transacao-individual': {
      id: '/simulador-transacao-individual'
      path: '/simulador-transacao-individual'
      fullPath: '/simulador-transacao-individual'
      preLoaderRoute: typeof SimuladorTransacaoIndividualRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SimuladorTransacaoIndividualRoute: SimuladorTransacaoIndividualRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
